name: proyectos_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  shared_preferences: ^2.0.5
  provider: ^6.1.2
  socket_io_client: ^2.0.0
  flutter_animate: ^4.5.2
  fluttertoast: ^8.2.8
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  path_provider: ^2.1.5
  pdf: ^3.8.0
  printing: ^5.13.4
  intl: ^0.19.0
  country_picker: ^2.0.27
  image_picker: ^1.1.2
  firebase_storage: ^12.3.7
  image_picker_web: ^4.0.0
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.1.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  cloud_functions: ^5.2.0
  firebase_database: ^11.2.0
  file_picker: ^8.1.6
  google_maps_flutter: ^2.10.0
  google_maps_flutter_web: ^0.5.10
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  location: ^7.0.1
  syncfusion_flutter_pdf: ^28.1.36
  share_plus: ^10.1.3
  animate_do: ^3.3.4
  connectivity_plus: ^6.1.2
  flutter_contacts: ^1.1.7+1
  google_ml_kit: ^0.19.0








dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_Bg.png
    - assets/logo_Bpa.png
    - assets/logo_Bpro.png
    - assets/logo_BI.png
    - assets/logo_Ba.png
    - assets/logoPaysat.png
    - assets/chip_tarjeta.png
    - assets/avatarLogoPaysat.png
    - assets/tarjetaVisaPaysat.jpg
    - assets/avatarIniciaSesion.png
    - assets/avatarRecuperarPassword.png
    - assets/avatarCrearUsuario.png
    - assets/iconoEnviar.png
    - assets/iconoRecargar.png
    - assets/IconocerrarSesion.png
    - assets/criptologo.png
    - assets/SatLogoSplash.png
    - assets/TarjetaHome.png
    - assets/amigosHome.png
    - assets/chatBootAvatar.png






